begin;
select plan(16);
select has_table('public','payroll_workbook_versions','versiona archivos exactos de pre-nómina');
select has_table('public','payroll_workbook_changes','conserva diferencias normalizadas');
select has_table('public','payroll_workbook_conflicts','expone conflictos Workera/RRHH');
select has_column('public','payroll_workbook_versions','content_sha256','guarda hash del archivo exacto');
select has_column('public','payroll_workbook_versions','storage_path','guarda ruta privada');
select has_column('public','payroll_workbook_versions','base_version_id','controla versión base');
select has_column('public','payroll_workbook_versions','period_start','identifica inicio del corte');
select has_column('public','payroll_workbook_versions','period_end','identifica fin del corte');
select has_column('public','payroll_workbook_changes','stable_key','relaciona por clave estable');
select has_column('public','payroll_workbook_changes','previous_value','conserva valor anterior');
select has_column('public','payroll_workbook_changes','new_value','conserva valor nuevo');
select has_column('public','payroll_workbook_conflicts','workera_value','conserva nuevo origen Workera');
select has_column('public','payroll_workbook_conflicts','rrhh_value','conserva veredicto RRHH');
select row_security_active('public','payroll_workbook_versions','versiones protegidas por RLS');
select row_security_active('public','payroll_workbook_changes','cambios protegidos por RLS');
select has_function('public','accept_payroll_workbook_version',array['uuid','uuid'],'confirmación transaccional e idempotente');
select * from finish();
rollback;
